# Generated by Django 2.2.3 on 2019-07-07 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_name', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('scan_target', models.CharField(max_length=50)),
                ('subnet', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Open_Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_numb', models.IntegerField()),
                ('host_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Host')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='scan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Scan'),
        ),
    ]
