# Generated by Django 2.2.3 on 2019-07-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190710_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='stauts',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
