# Generated by Django 2.2.3 on 2019-07-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_scan_stauts'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='task_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
